export const ROLES = {
  SUPERADMIN: "SUPERADMIN",
  ADMIN: "ADMIN",
  DOCTOR: "DOCTOR",
};

export const inputTypes = {
  TEXT: "TEXT",
  SELECT: "SELECT"
}

export const medCardInitialState = {
  "age": 0,
  "allergicToDrugs": "",
  "arterialPressure": "",
  "bimanualStudy": "",
  "birthday": "",
  "bloodHiv": "",
  "bloodHivPartner": "",
  "bloodRw": "",
  "bloodType": "",
  "bodyMassIndex": "",
  "bonePelvis": "",
  "cardiovascularSystem": "",
  "childbirthNumber": 0,
  "citizenship": "",
  "digestiveSystem": "",
  "doctor": "",
  "edema": "",
  "education": "ELEMENTARY",
  "email": "",
  "estimatedDateOfBirth": "",
  "examinationOfCervixInMirrors": "",
  "externalGenitalia": "",
  "fetalHeartbeat": "",
  "firstName": "",
  "firstVisitComplaints": "",
  "firstVisitDate": "",
  "firstVisitGrowth": 0,
  "firstVisitWeekOfPregnancy": 0,
  "firstVisitWeight": 0,
  "fromAnotherMedOrganizationReason": "",
  "gestationalAgeByLastMenstruation": 0,
  "gestationalAgeByUltrasound": 0,
  "husbandFirstName": "",
  "husbandLastName": "",
  "husbandMiddleName": "",
  "husbandPhoneNumber": "",
  "husbandPosition": "",
  "husbandWorkPlace": "",
  "insuranceNumber": "",
  "insuranceTerritoryName": "",
  "lastName": "",
  "lateRegistrationReason": "",
  "married": "YES",
  "middleName": "",
  "milkGlands": "",
  "nameOfAnotherMedOrganization": "",
  "pastIllnessesAndSurgeries": "",
  "patientAddress": "",
  "patientCategory": "",
  "patientHomePhoneNumber": "",
  "peripheralLymphNodes": "",
  "phoneNumber": "",
  "pin": "",
  "position": "",
  "pregnancyNumber": 0,
  "provisionalDiagnosis": "",
  "registrationDate": "",
  "relativeAddress": "",
  "relativePhoneNumber": "",
  "respiratorySystem": "",
  "rhFactorPartner": "",
  "rhFactorPregnant": "",
  "skinAndMucousMembranes": "",
  "thyroid": "",
  "titerRhFactorInTwentyEightMonth": "",
  "typeResultAppointments": {
    "additionalProp1": "",
    "additionalProp2": "",
    "additionalProp3": ""
  },
  "urinarySystem": "",
  "uterineFundusHeight": "",
  "vacationFromForPregnancy": "",
  "vacationUntilForPregnancy": "",
  "vaginalDischarge": "",
  "workConditions": "",
  "workPlace": "",
  "worksNow": true
}


